---
- name: Build and Push Docker Image from Localhost
  hosts: localhost
  become: true
 
  vars:
    image_name: grishma2477/myapp
    image_tag: latest
    dockerhub_username: grishma2477
    
  tasks:
    - name: Install Docker (Ubuntu/Debian)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Docker login
      shell: |
        echo "{{ dkr_pwd }}" | docker login -u "{{ dockerhub_username }}" --password-stdin
      

    - name: Build Docker image
      command: docker build -t {{ image_name }}:{{ image_tag }} .

    - name: Push Docker image
      command: docker push {{ image_name }}:{{ image_tag }}

- name: Pull and Run Container on Docker Server
  hosts: docker_server
  become: true 
  vars:
    image_name: grishma2477/myapp
    image_tag: latest
    container_name: myapp_container
  tasks:

    - name: Install Docker (CentOS/RHEL)
      yum:
        name: docker
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes


    - name: Pull image
      command: docker pull {{ image_name }}:{{ image_tag }}

    - name: Stop existing container if running
      command: docker rm -f {{ container_name }}

    - name: Run container
      command: >
        docker run -d
        --name {{ container_name }}
        -p 80:80
        --restart always
        {{ image_name }}:{{ image_tag }}